Encode base32 CID into an base36 CID
mlabs-haskell/nft-marketplace-server pull request #37
Opened 2022-07-25 23:09 UTC by Guilherme775

#22 

CIDS tested: 
![image](https://user-images.githubusercontent.com/55771765/180889455-2e1721d7-9a74-4658-89d8-81d38387476c.png)

CLI encoding:
![image](https://user-images.githubusercontent.com/55771765/180889478-970cda85-0c10-4e6b-bcdb-6b9d8ccbc652.png)

Database records with our encoding:
![image](https://user-images.githubusercontent.com/55771765/180889517-62d0d181-5fc3-4c97-a84f-016d01e6f413.png)

2022-07-26 07:45 UTC, t4ccer approved these changes
I didn't verified actual conversion algorithm as it seems rather magical. Make sure to open an issue to test all of it

2022-07-26 10:00 UTC, samuelWilliams99 requested changes
Could we not have used libraries like `base32`, say [this](https://hackage.haskell.org/package/base32-0.2.2.0/docs/Data-ByteString-Base32.html#v:decodeBase32) function? and `base36`?
Theres a lot of complex logic here.

2022-07-26 10:00 UTC, samuelWilliams99 commented on src/Ipfs.hs
> +           in ((newCarry `div` base) `shiftR` 0, Map.update (\_ -> Just (mod newCarry base `shiftR` 0)) (fst bit) b58Context')
Same here about shiftR 0

2022-07-26 10:00 UTC, samuelWilliams99 commented on src/Ipfs.hs
> +encodeBase32InBase36 (_ : xs) = Just $ (['k'] ++) $ encodeBase36 (alphabet36 base36) $ decodeBase32 xs (alphabet32 base32) (bitsPerChar32 base32)
always use `x:` over `[x] ++`

2022-07-26 10:01 UTC, samuelWilliams99 commented on src/Ipfs.hs
> +    insertInCodes _ codesMap = codesMap
(see next note)

2022-07-26 16:17 UTC, Guilherme775 commented
@samuelWilliams99 about using libraries, I tried a couple of ones, but unfortunately, none works as expected.

And about the other comments, thanks for the review, I'll fix these points.

2022-07-26 21:01 UTC, Guilherme775 commented on src/Ipfs.hs
> +              newCarry = carry' + ((256 * snd bit) `shiftR` 0)
That makes sense, I was drunk of JavaScript when I wrote this

2022-07-26 21:01 UTC, Guilherme775 commented on src/Ipfs.hs
> +          let bit = Map.toList b58Context' !! idx
Not in this case

2022-07-26 21:03 UTC, Guilherme775 commented on src/Ipfs.hs
> +    b58 [] _ = Map.empty
0 is the base case of this function.

2022-07-26 21:04 UTC, Guilherme775 commented on src/Ipfs.hs
> +    codes = insertInCodes (zip [0 ..] alphabet) Map.empty
Yes, don't know why was in my mind when I wrote this lol

2022-07-26 21:05 UTC, Guilherme775 commented on src/Ipfs.hs
> +decodeBase32 string alphabet bitsPerChar =
Solved!

2022-07-26 21:06 UTC, Guilherme775 commented on src/Ipfs.hs
> +data Base32 = Base32 {prefix32 :: String, name32 :: String, alphabet32 :: String, bitsPerChar32 :: Int}
yes, we're using just the alphabet basically, so I removed this datatype

2022-07-26 21:08 UTC, Guilherme775 commented on src/Ipfs.hs
> +encodeBase36 alphabet source =
I see, the original logic that I read to write this one was a lot of loops too, I tried to remove the majority of them and just keep the necessary ones, but maybe this is not fine enough.

Would be good if we create a task to make tests for those functions and also test their performance?

2022-07-26 21:09 UTC, Guilherme775 commented
For some reason in my local machine the "make format" is not working properly, can someone check this?

2022-07-27 09:14 UTC, samuelWilliams99 commented
Formatting fails

2022-07-27 09:28 UTC, samuelWilliams99 commented on src/Ipfs.hs
> +encodeBase36 alphabet source =
Yeah we can make that part of the testing requirements for this code.

2022-07-27 10:05 UTC, t4ccer commented
wrt formatting: https://github.com/mlabs-haskell/nft-marketplace-server/issues/38

2022-07-27 10:24 UTC, samuelWilliams99 commented on src/Ipfs.hs
> +      acc' <- acc
Taking an either then computing it seems the same as just using traverse over foldl at the start?

2022-07-27 10:24 UTC, samuelWilliams99 commented on src/Ipfs.hs
> +    Left err -> Left err
this is `out <$>`, no need for explicit case

2022-07-27 10:24 UTC, samuelWilliams99 commented on src/Ipfs.hs
> +      case Map.lookup c codes of
could lift the maybe into an either then compute it monadically, rather than the explicit case

2022-07-27 10:24 UTC, samuelWilliams99 commented on src/Ipfs.hs
> +  let b58List = reverse $ map snd $ Map.toList b58Context
Use `Map.elems` over `map snd . Map.toList`

2022-07-27 10:24 UTC, samuelWilliams99 commented on src/Ipfs.hs
> +               in pure (newCarry `div` base, Map.update (\_ -> Just (mod newCarry base)) (fst bit) b58Context')
Map.update with a const Just expression is just Map.insert

2022-07-27 10:24 UTC, samuelWilliams99 commented on src/Ipfs.hs
> +          Nothing -> Left $ "Cannot access index " ++ show it2 ++ " in " ++ show b58List
Failure at this point could mean a malformed input, this would likely be a better error message.

2022-07-27 10:24 UTC, samuelWilliams99 commented on src/NftStorage.hs
> +      Left err -> pure $ Left $ "error while enconding CID: " ++ err
An either case into an either case - could we not just rely on the Either monad?
using `first` to modify the error as needed.
Unsure if the `liftIO . putStrLn` above is needed.

2022-07-27 17:05 UTC, Guilherme775 commented on src/Ipfs.hs
> +      acc' <- acc
I used foldM here

2022-07-27 17:05 UTC, Guilherme775 commented on src/Ipfs.hs
> +      case Map.lookup c codes of
Yep

2022-07-27 17:06 UTC, Guilherme775 commented on src/Ipfs.hs
> +               in pure (newCarry `div` base, Map.update (\_ -> Just (mod newCarry base)) (fst bit) b58Context')
Oh, that makes sense

2022-07-27 17:06 UTC, Guilherme775 commented on src/NftStorage.hs
> +      Left err -> pure $ Left $ "error while enconding CID: " ++ err
bimap for the win

2022-07-27 17:07 UTC, Guilherme775 commented
@samuelWilliams99 if you can please run the formatter again here (don't know what is happening in my local env)

2022-07-28 09:19 UTC, samuelWilliams99 approved these changes

2022-07-28 09:23 UTC, t4ccer commented
@Guilherme775 What's your issue with formatting? Do you run `make format` inside nix shell?

2022-07-28 17:28 UTC, rynoV requested changes
I tested this out locally with a new image and the CID matched what was expected. This also fixes the issue with the name and description not showing on the frontend:

![2022-07-28-112221_806x403_scrot](https://user-images.githubusercontent.com/35615725/181599763-99705c71-9c64-45ff-9d7b-66dcf005d943.png)
![2022-07-28-112236_845x728_scrot](https://user-images.githubusercontent.com/35615725/181599769-9bf5d090-96d0-4e16-8220-5851c3aa9abd.png)

("Moss" is the NFT minted using these changes, see [cnft](0f2f52d519f02224a821b6f843d6eb8ecf98cd6a17faeb8d77304edcf5659979) and [sgnft](https://testnet.cardanoscan.io/transaction/a1a8260cb29a6a3d72960397aa04f984d2a2189c455458f4dd25830edd80305c))

The code seems quite involved. Was it not the case that there are just some prefixes in the base32 CID then the rest of the string is just regular base32?

2022-07-28 19:24 UTC, rynoV requested changes

2022-07-28 19:24 UTC, rynoV commented on src/Ipfs.hs
> +encodeBase32InBase36 :: String -> Either String String
We should also somehow make it clear in the signature of this function that it operates on base32 IPFS CIDs and not arbitrary base32 strings. Maybe just change the name and add a doc comment

2022-07-28 19:25 UTC, t4ccer commented on src/Ipfs.hs
> +encodeBase32InBase36 :: String -> Either String String
We already have `CID` type right? We can introduce phantom parameter to indicate base. It will be useful later when we'll need code to distinguish between different bases instead of assuming base32

2022-07-28 19:26 UTC, t4ccer commented on src/Ipfs.hs
> +encodeBase32InBase36 :: String -> Either String String
`encodeBase32InBase36 :: CID Base32 -> Either String (CID Base36)` looks clean

2022-07-29 14:28 UTC, samuelWilliams99 commented
> The code seems quite involved. Was it not the case that there are just some prefixes in the base32 CID then the rest of the string is just regular base32?

I questioned the lack of external libraries for the logic, apparently they weren't sufficient.
Given we're on a bit of a time limit, we can create a ticket to see if we can refactor this to something external later

2022-08-01 16:58 UTC, rynoV commented
> We should also somehow make it clear in the signature of this function that it operates on base32 IPFS CIDs and not arbitrary base32 strings

Not sure if this is much better as I just changed most functions to deal with Text instead of CID (I don't have haskell development setup locally so it's a slow process to change types of things, and we're in a bit of a rush). This is a start though, at least the encoding function's type makes it clear now what it operates on. We can improve on this later, possibly in #39 

cc @samuelWilliams99

2022-08-01 17:12 UTC, samuelWilliams99 commented on src/Ipfs.hs
> +newtype CID base = CID {unCID :: Text}
the bases could be a sum type together, and we can make the `base` be that, or just use a Nat
`newtype CID (base :: Nat) = CID {unCID :: Text}`
would have a neater look

2022-08-01 17:21 UTC, samuelWilliams99 approved these changes

2022-08-01 17:25 UTC, merged